
#设置启用的环境
spring:
  profiles:
    active: dev

---
server:
  port: 8080
spring:
  application:
    name: xd_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:
      username:
      password:
  config:
    activate:
      on-profile: dev
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#文件上传的路径
xd:
  path:


---
#生产
server:
  port: 8080
spring:
  application:
    name: xd_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:
      username:
      password:
  config:
    activate:
      on-profile: pro
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#文件上传的路径
xd:
  path: /usr/local/app/pic